#!/usr/bin/env python3
# Build-time asset converter for Sprint (NOT shipped logic; run by hand).
#
# Converts the CC0 PySprint assets (github.com/salem-ok/PySprint) into the
# 1-bit images + Lua track data this Playdate port consumes -- the same kind
# of color->1-bit conversion the rest of classics/ does for its source art.
#
#   /tmp/ppenv/bin/python convert.py
#
# Sources are read from $PYSPRINT_SRC (default /tmp/pysprint_src). Outputs go
# into images/ and the generated trackN_data.lua / trackN_mask.lua files. All
# eight tracks are 640x400 logical; we keep physics there and render at S=0.6
# -> a 384x240 playfield centred on the 400x240 screen.

import json, os
from PIL import Image, ImageFilter, ImageOps

SRC = os.environ.get("PYSPRINT_SRC", "/tmp/pysprint_src")
HERE = os.path.dirname(os.path.abspath(__file__))
IMG = os.path.join(HERE, "images")
CAR = os.path.join(IMG, "car")
os.makedirs(CAR, exist_ok=True)

S = 0.6
LOGW, LOGH = 640, 400
SCRW, SCRH = round(LOGW * S), round(LOGH * S)   # 384 x 240
OX = (400 - SCRW) // 2                           # 8
NTRACKS = 8

def asset(name):
    return os.path.join(SRC, "Assets", name)

# ---------------------------------------------------------------- tracks
def convert_track(idx):
    d = json.load(open(os.path.join(SRC, "Assets", "tracks", "SuperSprintTrack%d.json" % idx)))
    m = Image.open(asset("SuperSprintTrack%dMask.png" % idx)).convert("L")
    sx, sy = d["first_car_start_position"]
    # polarity: the start tile must be drivable. Average a small box to be safe.
    box = m.crop((sx - 3, sy - 3, sx + 3, sy + 3))
    drv_bright = (sum(box.getdata()) / (box.width * box.height)) > 127

    # display: solid black road (so white cars read), dithered source art only
    # in the wall/grandstand areas. Far more legible than dithering it all.
    art = Image.open(asset("SuperSprintTrack%d.png" % idx)).convert("RGB").resize((SCRW, SCRH), Image.BILINEAR).convert("1")
    ms = m.resize((SCRW, SCRH), Image.BILINEAR)
    disp = Image.new("1", (SCRW, SCRH), 0)
    ap, msp, dp = art.load(), ms.load(), disp.load()
    for y in range(SCRH):
        for x in range(SCRW):
            drivable = (msp[x, y] > 127) == drv_bright
            dp[x, y] = 0 if drivable else ap[x, y]
    disp.save(os.path.join(IMG, "track%d.png" % idx))

    # collision mask -> baked '#'(drivable)/'.'(wall) grid, downsampled by D
    D = 2
    GW, GH = LOGW // D, LOGH // D                 # 320 x 200
    mg = m.resize((GW, GH), Image.BILINEAR)
    rows = []
    for gy in range(GH):
        rows.append("".join("#" if (mg.getpixel((gx, gy)) > 127) == drv_bright else "." for gx in range(GW)))
    with open(os.path.join(HERE, "track%d_mask.lua" % idx), "w") as f:
        f.write("-- GENERATED by convert.py -- baked collision grid for track %d.\n" % idx)
        f.write("-- '#' = drivable, '.' = wall. From SuperSprintTrack%dMask.png (PySprint, CC0).\n" % idx)
        f.write("Track%dMask = {\n  D = %d, W = %d, H = %d,\n  rows = {\n" % (idx, D, GW, GH))
        for r in rows:
            f.write('    "%s",\n' % r)
        f.write("  },\n}\n")

    # geometry (logical 640x400 coords; physics runs there). gates = external
    # <-> internal point pairs in race order; their midpoints are the line.
    eg, ig = d["external_gate_points"], d["internal_gate_points"]
    n = min(len(eg), len(ig))
    with open(os.path.join(HERE, "track%d_data.lua" % idx), "w") as f:
        f.write("-- GENERATED by convert.py -- track %d geometry (logical 640x400),\n" % idx)
        f.write("-- from SuperSprintTrack%d.json (PySprint, CC0).\n" % idx)
        f.write("Track%d = {\n" % idx)
        f.write("  name = %r,\n" % ("TRACK %d" % idx))
        f.write("  difficulty = %r,\n" % d.get("difficulty_level", ""))
        st = d["first_car_start_position"]
        f.write("  start = { x = %d, y = %d, ang = %d },\n" % (st[0], st[1], d["start_sprite_angle"]))
        fr = d["finish_line_rect"]
        f.write("  finishRect = { %d, %d, %d, %d },\n" % (fr[0], fr[1], fr[2], fr[3]))
        f.write("  finishDir = %d,\n" % d["finish_line_direction"])
        f.write("  gates = {\n")
        for i in range(n):
            f.write("    { ex = %d, ey = %d, ix = %d, iy = %d },\n" % (eg[i][0], eg[i][1], ig[i][0], ig[i][1]))
        f.write("  },\n}\n")
    print("track%d: %d gates, %s, %s=drivable" % (idx, n, d.get("difficulty_level", "?"), "bright" if drv_bright else "dark"))

for i in range(1, NTRACKS + 1):
    convert_track(i)

# ---------------------------------------------------------------- cars
# 16 sprite angles. Player = solid white silhouette; drone = hollow outline,
# so the two read apart in 1-bit even though colour is gone.
def alpha_of(im):
    a = im.split()[3]
    if a.getextrema() == (255, 255):           # no real alpha: key out corner
        bgc = im.getpixel((0, 0))[:3]
        gray = Image.new("L", im.size, 0)
        px = im.load(); gp = gray.load()
        for y in range(im.height):
            for x in range(im.width):
                r, g, b, _ = px[x, y]
                gp[x, y] = 0 if abs(r - bgc[0]) + abs(g - bgc[1]) + abs(b - bgc[2]) < 40 else 255
        return gray
    return a.point(lambda v: 255 if v > 128 else 0)

def car_set(prefix, outpref, outline):
    w = h = 0
    for a in range(16):
        im = Image.open(asset("%s%d.png" % (prefix, a))).convert("RGBA")
        mask = alpha_of(im)
        if outline:
            eroded = mask.filter(ImageFilter.MinFilter(3))
            edge = Image.new("L", mask.size, 0)
            mp, ep, erp = mask.load(), edge.load(), eroded.load()
            for y in range(mask.height):
                for x in range(mask.width):
                    ep[x, y] = 255 if (mp[x, y] > 128 and erp[x, y] <= 128) else 0
            vis = edge
        else:
            vis = mask
        out = Image.new("RGBA", im.size, (0, 0, 0, 0))
        op = out.load(); vp = vis.load()
        for y in range(im.height):
            for x in range(im.width):
                if vp[x, y] > 128:
                    op[x, y] = (255, 255, 255, 255)
        w, h = round(im.width * S), round(im.height * S)
        out = out.resize((w, h), Image.NEAREST)
        out.save(os.path.join(CAR, "%s%02d.png" % (outpref, a)))
    print("car set", outpref, "16 sprites", (w, h))

car_set("RedCar", "p", outline=False)        # player: solid
car_set("RedCarDrone", "d", outline=True)    # drones: hollow

# ---------------------------------------------------------------- title
for cand in ("SuperSprintSplashScreen.png", "SplashScreen.png"):
    p = asset(cand)
    if os.path.exists(p):
        ti = Image.open(p).convert("RGB")
        ti = ImageOps.pad(ti, (400, 240), color=(0, 0, 0)).convert("1")
        ti.save(os.path.join(IMG, "title.png"))
        print("title.png from", cand, ti.size)
        break

print("done. OX =", OX, "playfield", SCRW, "x", SCRH)
